defaults:
  - _self_

method: mean-teacher-cps

train:
  total_epochs: 200
  validation_interval: 5

init:
  _target_: trainer.MeanTeacherCPS
  supervised_criterion:
    _target_: torch.nn.MSELoss
  consistency_weight: 1.0      # weight for Mean Teacher consistency
  ema_decay: 0.99
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.001
    weight_decay: 0.005
  scheduler:
    _target_: torch.optim.lr_scheduler.StepLR
    _partial_: true
    step_size: 1
    gamma: 0.98
