defaults:
  - _self_

name: attentivefp

init:
  _target_: models.AttentiveFPRegressor
  _partial_: false
  in_channels: 11
  hidden_channels: 200
  out_channels: 1
  edge_dim: 4
  num_layers: 3
  num_timesteps: 3
  dropout: 0.0
