defaults:
  - _self_

name: schnet

init:
  _target_: models.SchNetRegressor
  _partial_: false
  hidden_channels: 128
  num_filters: 128
  num_interactions: 6
  num_gaussians: 50
  cutoff: 10.0
  readout: add
  dropout: 0.2
  add_mlp_head: true
  mlp_hidden: 128
  out_channels: 1
