defaults:
  - _self_

name: visnet

init:
  _target_: models.ViSNetRegressor
  _partial_: false
  lmax: 2
  vecnorm_type: null
  trainable_vecnorm: false
  num_heads: 8
  num_layers: 4
  hidden_channels: 64
  num_rbf: 32
  trainable_rbf: false
  max_z: 100
  cutoff: 5.0
  max_num_neighbors: 32
  vertex: false
  reduce_op: sum          # sum|mean
  mean: null
  std: null
  derivative: false
  out_channels: 1
  dropout: 0.0
  mlp_layers: 2
  mlp_hidden: 256