defaults:
  - _self_

_target_: logger.WandBLogger
group: ${dataset.dataset_name} # Name of the group for wandb
name: ${model.name}_seed=${seed} # Name of the run for wandb
job_type: test
entity: victorwinther-technical-university-of-denmark-
project_name: semi-supervised-learning-for-drug-discovery
disable: false
local_dir: ./logs #Directory to save logs
