defaults:
  - _self_

_target_: logger.WandBLogger
group: ${model.name}_${dataset.dataset_name}              # group by model
name: ${model.name}_seed=${seed}  # run name
job_type: ${trainer.method}       # "semi-supervised-ensemble"
entity: victorwinther-technical-university-of-denmark-
project_name: semi-supervised-learning-for-drug-discovery
disable: false
local_dir: ./logs
