defaults:
  - dataset: qm9
  - trainer: mean-teacher
  - logger: wandb
  - model: dimenetpp
  - _self_

seed: 0
device: unset
force_deterministic: False
debug_mode: False
result_dir: ./results
compile_model: false
